sudo: required
services:
  - docker

before_install:
  - docker build -t 20831744/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run 20831744/react-test npm test --coverage

after_sucess:

  - docker build -t 20831744/multi-client ./client
  - docker build -t 20831744/multi-server ./server
  - docker build -t 20831744/multi-nginx ./nginx
  - docker build -t 20831744/multi-worker ./worker

  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push 20831744/multi-client
  - docker push 20831744/multi-nginx
  - docker push 20831744/multi-server
  - docker push 20831744/multi-worker
